version: '3'
services:
    springboot:
        container_name: springboot
        image: 100598/springboot:1.0
        ports: 
        - 9090:8080
    mysql:
        container_name: mysql
        image: mysql:5.7
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=rohit
        - MYSQL_PASSWORD=1234
        - MYSQL_DATABASE=USERS
        volumes:
        - appvolume:/var/lib/mysql
volumes:
    appvolume:  
